// src/constants/platforms.js

const platforms = [
  { name: "Facebook", image: require("../assets/platforms/facebook.png") },
  { name: "Instagram", image: require("../assets/platforms/instagram.png") },
  { name: "Twitter", image: require("../assets/platforms/twitter.png") },
  { name: "LinkedIn", image: require("../assets/platforms/linkedin.png") },
  { name: "TikTok", image: require("../assets/platforms/tiktok.png") },
  { name: "NordVPN", image: require("../assets/platforms/nordvpn.png") },
  { name: "ExpressVPN", image: require("../assets/platforms/expressvpn.png") },
  { name: "Surfshark", image: require("../assets/platforms/surfshark.png") },
  { name: "CyberGhost", image: require("../assets/platforms/cyberghost.png") },
  { name: "ProtonVPN", image: require("../assets/platforms/protonvpn.png") },
  { name: "Private Internet Access", image: require("../assets/platforms/private-internet-access.png") },
  { name: "TunnelBear", image: require("../assets/platforms/tunnelbear.png") },
  { name: "Windscribe", image: require("../assets/platforms/windscribe.png") },
  { name: "Gmail", image: require("../assets/platforms/gmail.png") },
  { name: "Google Voice", image: require("../assets/platforms/google-voice.png") },
  { name: "Text Now", image: require("../assets/platforms/text-now.png") },
  { name: "Text Plus", image: require("../assets/platforms/text-plus.png") },
  { name: "Yahoo Mail", image: require("../assets/platforms/yahoo.png") },
  { name: "Outlook", image: require("../assets/platforms/outlook.png") },
  { name: "ProtonMail", image: require("../assets/platforms/protonmail.png") },
  { name: "Zoho Mail", image: require("../assets/platforms/zoho.png") },
  { name: "iCloud Mail", image: require("../assets/platforms/icloud.png") },
  { name: "Signal", image: require("../assets/platforms/signal.png") },
  { name: "Messenger", image: require("../assets/platforms/messenger.png") },
  { name: "WeChat", image: require("../assets/platforms/wechat.png") },
  { name: "Line", image: require("../assets/platforms/line.png") },
  { name: "Skype", image: require("../assets/platforms/skype.png") },
  { name: "Viber", image: require("../assets/platforms/viber.png") },
  { name: "Discord", image: require("../assets/platforms/discord.png") },
  { name: "Netflix", image: require("../assets/platforms/netflix.png") },
  { name: "Amazon Prime Video", image: require("../assets/platforms/prime-video.png") },
  { name: "Hulu", image: require("../assets/platforms/hulu.png") },
  { name: "Disney+", image: require("../assets/platforms/disney.png") },
  { name: "HBO Max", image: require("../assets/platforms/hbo-max.png") },
  { name: "Apple TV+", image: require("../assets/platforms/apple-tv.png") },
  { name: "Spotify", image: require("../assets/platforms/spotify.png") },
  { name: "YouTube Premium", image: require("../assets/platforms/youtube-premium.png") },
  { name: "Tidal", image: require("../assets/platforms/tidal.png") },
  { name: "Deezer", image: require("../assets/platforms/deezer.png") },
  { name: "Crunchyroll", image: require("../assets/platforms/crunchyroll.png") },
  { name: "OnlyFans", image: require("../assets/platforms/onlyfans.png") },
  { name: "Patreon", image: require("../assets/platforms/patreon.png") },
];

export default platforms;
